In [ ]:

!pip install -q ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd

Mengambil dataset Online Retail dari UCI

In [ ]:
online_retail = fetch_ucirepo(id=352)

**1. Menampilkan Data Mentah (Before Preprocessing)**

In [ ]:
df_raw = online_retail.data.features.copy()

print("Ukuran dataset:", df_raw.shape)

print("\nNama kolom:")
print(df_raw.columns.tolist())

print("\nLima baris pertama:")
display(df_raw.head())

Ukuran dataset: (541909, 6)

Nama kolom:
['Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Lima baris pertama:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

Memeriksa ukuran data

In [ ]:
print("Ukuran fitur:", online_retail.data.features.shape)

Ukuran fitur: (541909, 6)

Pemeriksaan awal kualitas data

In [ ]:
df = online_retail.data.features.copy()

1. Informasi tipe data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Description  540455 non-null  object
 1   Quantity     541909 non-null  int64
 2   InvoiceDate  541909 non-null  object
 3   UnitPrice    541909 non-null  float64
 4   CustomerID   406829 non-null  float64
 5   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(3)
memory usage: 24.8+ MB

2. Jumlah nilai kosong

In [ ]:
print("\nJumlah nilai kosong:")
display(df.isnull().sum())

Jumlah nilai kosong:

Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

3. Jumlah baris duplikat

In [ ]:
print("\nJumlah baris duplikat:")
print(df.duplicated().sum())

Jumlah baris duplikat:
6007

4. Statistik deskriptif

In [ ]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Description,540455,4223,WHITE HANGING HEART T-LIGHT HOLDER,2369,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,541909.0,NaN,NaN,NaN,9.55225,218.081158,-80995.0,1.0,3.0,10.0,80995.0
InvoiceDate,541909,23260,10/31/2011 14:41,1114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UnitPrice,541909.0,NaN,NaN,NaN,4.611114,96.759853,-11062.06,1.25,2.08,4.13,38970.0
CustomerID,406829.0,NaN,NaN,NaN,15287.69057,1713.600303,12346.0,13953.0,15152.0,16791.0,18287.0
Country,541909,38,United Kingdom,495478,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Memeriksa bagian dataset yang tersedia dari UCI

In [ ]:
print("Kolom fitur:")
print(online_retail.data.features.columns.tolist())

print("\nKolom ID:")
if online_retail.data.ids is not None:
    print(online_retail.data.ids.columns.tolist())
    display(online_retail.data.ids.head())
else:
    print("Tidak ada kolom ID terpisah.")

print("\nData asli tersedia:")
print(online_retail.data.original is not None)

Kolom fitur:
['Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Kolom ID:
['InvoiceNo', 'StockCode']

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B
3    536365    84029G
4    536365    84029E

Data asli tersedia:
True

Menggabungkan kolom fitur dan ID

In [ ]:
df_raw = pd.concat(
    [
        online_retail.data.features,
        online_retail.data.ids
    ],
    axis=1
).copy()

Membuat data kerja dari data mentah lengkap

In [ ]:
df = df_raw.copy()

print("Ukuran dataset lengkap:", df.shape)
print("\nDaftar kolom:")
print(df.columns.tolist())

print("\nLima baris pertama:")
display(df.head())

Ukuran dataset lengkap: (541909, 8)

Daftar kolom:
['Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'InvoiceNo', 'StockCode']

Lima baris pertama:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,536365,85123A
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,536365,71053
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,536365,84406B
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,536365,84029G
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,536365,84029E

**2. Data Preprocessing**

Pemeriksaan kualitas dataset lengkap

In [ ]:
print("Ukuran data:", df.shape)

print("\nJumlah missing values:")
display(df.isnull().sum())

print("\nJumlah baris duplikat:")
print(df.duplicated().sum())

print("\nTipe data:")
display(df.dtypes)

Ukuran data: (541909, 8)

Jumlah missing values:

Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
InvoiceNo           0
StockCode           0
dtype: int64

Jumlah baris duplikat:
5268

Tipe data:

Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
InvoiceNo       object
StockCode       object
dtype: object

**2.1 Penanganan Data Duplikat**

Menghitung duplikat sebelum dibersihkan

In [ ]:
duplikat_sebelum = df.duplicated().sum()

Menghapus baris duplikat

In [ ]:
df = df.drop_duplicates().copy()

Memeriksa hasil

In [ ]:
print("Duplikat sebelum:", duplikat_sebelum)
print("Duplikat sesudah:", df.duplicated().sum())
print("Ukuran data sesudah:", df.shape)

Duplikat sebelum: 5268
Duplikat sesudah: 0
Ukuran data sesudah: (536641, 8)

**2.2 Pemeriksaan Missing Values**

Memeriksa nilai kosong setelah penghapusan duplikat

In [ ]:
print("Jumlah missing values setelah penghapusan duplikat:")
display(df.isnull().sum())

print("\nPersentase missing values (%):")
display((df.isnull().mean() * 100).round(2))

Jumlah missing values setelah penghapusan duplikat:

Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
InvoiceNo           0
StockCode           0
dtype: int64

Persentase missing values (%):

Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     25.16
Country         0.00
InvoiceNo       0.00
StockCode       0.00
dtype: float64

**2.3 Penanganan Missing Values**

Menangani Description yang kosong

In [ ]:
df["Description"] = df["Description"].fillna("Unknown")

CustomerID tidak diisi dengan nilai buatan
karena merupakan identitas pelanggan

In [ ]:
print("Missing values setelah penanganan:")
display(df.isnull().sum())

print("\nUkuran dataset:", df.shape)

Missing values setelah penanganan:

Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
InvoiceNo           0
StockCode           0
dtype: int64

Ukuran dataset: (536641, 8)

**2.4 Transformasi Tipe Data**

Mengubah InvoiceDate menjadi tipe datetime

In [33]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)

print("Tipe data setelah transformasi:")
display(df.dtypes)

print("\nJumlah InvoiceDate yang kosong:")
print(df["InvoiceDate"].isnull().sum())

Tipe data setelah transformasi:

Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
InvoiceNo              object
StockCode              object
dtype: object

Jumlah InvoiceDate yang kosong:
0

**2.5 Pemeriksaan Nilai Tidak Wajar**

Memeriksa nilai Quantity dan UnitPrice

In [34]:
print("Quantity negatif:", (df["Quantity"] < 0).sum())
print("Quantity nol:", (df["Quantity"] == 0).sum())

print("UnitPrice negatif:", (df["UnitPrice"] < 0).sum())
print("UnitPrice nol:", (df["UnitPrice"] == 0).sum())

print("\nContoh transaksi dengan Quantity negatif:")
display(df[df["Quantity"] < 0].head())

print("\nContoh transaksi dengan UnitPrice negatif:")
display(df[df["UnitPrice"] < 0])

Quantity negatif: 10587
Quantity nol: 0
UnitPrice negatif: 2
UnitPrice nol: 2510

Contoh transaksi dengan Quantity negatif:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
141,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,C536379,D
154,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,C536383,35004C
235,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,C536391,22556
236,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,C536391,21984
237,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,C536391,21983

Contoh transaksi dengan UnitPrice negatif:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
299983,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom,A563186,B
299984,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom,A563187,B

**2.6 Analisis Transaksi Khusus**

Memeriksa transaksi pembatalan

In [35]:
print(
    "Invoice dengan awalan C:",
    df["InvoiceNo"].astype(str).str.startswith("C").sum()
)

Invoice dengan awalan C: 9251

Memeriksa transaksi dengan harga nol

In [36]:
print("\nContoh transaksi dengan UnitPrice nol:")
display(df[df["UnitPrice"] == 0].head(10))

#print("\nContoh transaksi dengan UnitPrice nol:")
display(df[df["UnitPrice"] == 0].head(10))

print("\nTransaksi dengan UnitPrice negatif:")
display(df[df["UnitPrice"] < 0])

Contoh transaksi dengan UnitPrice nol:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
622,Unknown,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom,536414,22139
1970,Unknown,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom,536545,21134
1971,Unknown,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,536546,22145
1972,Unknown,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,536547,37509
1987,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,536549,85226A
1988,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,536550,85044
2024,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,536552,20950
2025,Unknown,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom,536553,37461
2026,Unknown,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom,536554,84670
2406,Unknown,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom,536589,21777

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
622,Unknown,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom,536414,22139
1970,Unknown,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom,536545,21134
1971,Unknown,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,536546,22145
1972,Unknown,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom,536547,37509
1987,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,536549,85226A
1988,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,536550,85044
2024,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom,536552,20950
2025,Unknown,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom,536553,37461
2026,Unknown,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom,536554,84670
2406,Unknown,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom,536589,21777

Transaksi dengan UnitPrice negatif:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
299983,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom,A563186,B
299984,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom,A563187,B

Memeriksa deskripsi produk yang berkaitan

In [37]:
print("\nDeskripsi pada transaksi harga negatif:")
display(
    df.loc[df["UnitPrice"] < 0, ["Description", "Quantity", "UnitPrice", "InvoiceNo"]]
)

Deskripsi pada transaksi harga negatif:

            Description  Quantity  UnitPrice InvoiceNo
299983  Adjust bad debt         1  -11062.06   A563186
299984  Adjust bad debt         1  -11062.06   A563187

**2.7 Penanganan Transaksi dengan Harga Negatif**

Menghitung transaksi dengan harga negatif

In [38]:
harga_negatif = (df["UnitPrice"] < 0).sum()

print("Transaksi dengan harga negatif sebelum:", harga_negatif)

Transaksi dengan harga negatif sebelum: 2

Mengecualikan harga negatif dari dataset analisis penjualan

In [39]:
df = df[df["UnitPrice"] >= 0].copy()

print("Transaksi dengan harga negatif sesudah:", (df["UnitPrice"] < 0).sum())
print("Ukuran dataset setelah penanganan:", df.shape)

Transaksi dengan harga negatif sesudah: 0
Ukuran dataset setelah penanganan: (536639, 8)

**3. Hasil Setelah Preprocessing (After)**

In [40]:

print("=== AFTER PREPROCESSING ===")

print("Ukuran dataset:", df.shape)

print("\nLima baris pertama:")
display(df.head())

print("\nJumlah missing values:")
display(df.isnull().sum())

print("\nJumlah duplikat:")
print(df.duplicated().sum())

print("\nTipe data:")
display(df.dtypes)

=== AFTER PREPROCESSING ===
Ukuran dataset: (536639, 8)

Lima baris pertama:

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceNo,StockCode
0,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,536365,85123A
1,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,536365,71053
2,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,536365,84406B
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,536365,84029G
4,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,536365,84029E

Jumlah missing values:

Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135035
Country             0
InvoiceNo           0
StockCode           0
dtype: int64

Jumlah duplikat:
0

Tipe data:

Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
InvoiceNo              object
StockCode              object
dtype: object

**4. Perbandingan Sebelum dan Sesudah Preprocessing**

Perbandingan kondisi sebelum dan sesudah preprocessing

In [42]:
perbandingan = pd.DataFrame({
    "Keterangan": [
        "Jumlah baris",
        "Jumlah kolom",
        "Missing Description",
        "Missing CustomerID",
        "Jumlah duplikat",
        "Quantity negatif",
        "UnitPrice negatif",
        "UnitPrice nol"
    ],
    "Before": [
        len(online_retail.data.features),
        len(df_raw.columns),
        online_retail.data.features["Description"].isnull().sum(),
        online_retail.data.features["CustomerID"].isnull().sum(),
        df_raw.duplicated().sum(),
        (online_retail.data.features["Quantity"] < 0).sum(),
        (online_retail.data.features["UnitPrice"] < 0).sum(),
        (online_retail.data.features["UnitPrice"] == 0).sum()
    ],
    "After": [
        len(df),
        len(df.columns),
        df["Description"].isnull().sum(),
        df["CustomerID"].isnull().sum(),
        df.duplicated().sum(),
        (df["Quantity"] < 0).sum(),
        (df["UnitPrice"] < 0).sum(),
        (df["UnitPrice"] == 0).sum()
    ]
})

display(perbandingan)

            Keterangan  Before   After
0         Jumlah baris  541909  536639
1         Jumlah kolom       8       8
2  Missing Description    1454       0
3   Missing CustomerID  135080  135035
4      Jumlah duplikat    5268       0
5     Quantity negatif   10624   10587
6    UnitPrice negatif       2       0
7        UnitPrice nol    2515    2510

**5. Kesimpulan**

Berdasarkan proses preprocessing pada dataset Online Retail, ditemukan beberapa masalah kualitas data, yaitu nilai kosong pada kolom Description dan CustomerID, data duplikat, perbedaan tipe data, serta transaksi dengan nilai UnitPrice negatif.

Preprocessing dilakukan dengan menghapus baris duplikat, mengganti Description yang kosong dengan label "Unknown", mengubah InvoiceDate menjadi tipe datetime, dan mengecualikan dua transaksi dengan UnitPrice negatif dari dataset analisis penjualan.

Setelah preprocessing, jumlah data berkurang dari 541.909 menjadi 536.639 baris. Jumlah duplikat menjadi nol, nilai kosong pada Description berhasil ditangani, dan tipe data tanggal berhasil diperbaiki. Sementara itu, nilai kosong pada CustomerID dan Quantity negatif tetap dipertahankan karena memerlukan pertimbangan lebih lanjut berdasarkan tujuan analisis.

Dengan demikian, data telah melalui tahap pembersihan dan transformasi awal sehingga lebih siap digunakan untuk analisis data mining berikutnya.

Menyimpan dataset hasil preprocessing

In [43]:
df.to_csv("online_retail_cleaned.csv", index=False)

print("Dataset berhasil disimpan!")
print("Ukuran akhir:", df.shape)

Dataset berhasil disimpan!
Ukuran akhir: (536639, 8)